### ISSUE TITLE
[editor]: Support dat in preview

### ISSUE THREAD

**Issue by LordBuffalo1227** [AdamRaichu/vscode-zip-viewer#139]
Please add support for `.dat` files to the editor preview.

*Generated by `adamraichu.zip-viewer`*

**Comment by AdamRaichu** [comment]
Unfortunately, `.dat` is most often in binary format, rather than text, so I won't be adding this file extension. Either use `textFileAssociations`, or wait for me to finally make feature for text files by glob pattern. (Sorry I haven't worked on this project much, I've had other interests and obligations occupying my time recently.)

**Comment by AdamRaichu** [comment]
See #85.
