### ISSUE TITLE
[editor]: Support custom handlers for preview

### ISSUE THREAD

**Issue by Jeff-Walker** [AdamRaichu/vscode-zip-viewer#76]
Please add support for `.class` files to the editor preview.

I use Intellij IDEA to open class files, but not everyone would, so add support for custom apps.

*Generated by `adamraichu.zip-viewer`*

**Comment by AdamRaichu** [comment]
What do you mean by "custom handlers" for preview? What do you have in mind? Would you want me to implement some kind of API?

**Comment by Jeff-Walker** [comment]
Just an external command? Have a list of file extension to a command. So
I'd put in ... /idea.exe or whatever to extract and open the app. Not sure
how vs code handles filetype editors, but in most cases there's an api. Is
so maybe use that.

**Comment by AdamRaichu** [comment]
A couple things come to mind after reading that.

1. It seems like it could be a security vulnerability to have the extension run a command on opening a subfile of a zip file. (For example, a custom command could be set in the workspace settings which installs unwanted software.)
2. I'm trying to make all features work in the browser version of vscode (vscode.dev / github.dev) as well as on a computer as not many good extensions are compatible with the browser. Running a command in the manner you suggest is not possible there.

Here are a couple solutions/alternatives which would do something similar to what you want:

1. Use the [Selective Extraction](https://github.com/AdamRaichu/vscode-zip-viewer#selective-extraction) feature to extract the class files you are trying to read, and open them manually in IDEA.
2. I would be willing to implement some way of opening raw `.class` files in vscode if I had a **JavaScript** library which could decompile them. If you know of or could find such a library I could implement that.


> Not sure how vs code handles filetype editors, but in most cases there's an api.

The method vscode uses for custom editors is based on file path (name and location in folders). However, that requires having the actual file outside of the zip file, and so is outside the scope of this particular extension. However, see point 2 under solutions above; I would happy to make another extension if I had a library for it.

All of that said, I'm closing as `wontfix` because it is out of scope for this extension. (In the same way, I didn't have this extension display PDF files because you can simply selectively extract them and view with another extension.)

**Comment by AdamRaichu** [comment]
While I'm sorry to give a negative response, I do appreciate the feedback! Please continue to let me know if there are features you would like, or if you find any problems.
